version: '3.9'

services:
  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./data:/data
    networks:
      - verve-network

  verve-app:
    depends_on:
      - amqp
      - redis
    container_name: verve-app
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - 8080:8080
    networks:
      - verve-network
    environment:
      - redis-srv=redis
      - redis-port=6379
      - mq-user=guest
      - mq-pass=guest
      - mq-srv=amqp

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    networks:
      - verve-network

  amqp:
    image: rabbitmq:3-management
    ports:
      - 15672:15672
      - 5672:5672
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 5s
      timeout: 15s
      retries: 1
    networks:
      - verve-network

networks:
  verve-network:
